### ISSUE TITLE
Run on Windows 11 Native

### ISSUE THREAD

**Issue by phreed** [banach-space/clang-tutor#29]
Work with `conda-forge` packages. 
The following environment may be sufficient.

The 
```yaml
name: llvm

channels:
  - conda-forge
  - defaults

dependencies:

# build tools
- cmake
- conan 
- ninja
# - vcpkg

# https://github.com/conda-forge/clangdev-feedstock
- clang
- clang-format
# - clang-format-16
- clang-tools
- clangdev
# - clangxx
- libclang
- libclang-cpp
# - libclang-cpp16
# - libclang13
# - python-clang

# https://github.com/conda-forge/llvmdev-feedstock
- libllvm16
- lit
- llvm
- llvm-tools 
- llvmdev
```

As it is `conda` it may work for any platform.
